#!/usr/bin/env bash
# Run from repo root: bash frontend/scripts/download-car-logos.sh
# Downloads SVGs into frontend/public/logos/
# Note: raw.githubusercontent.com/nicktaras/car-makes-icons paths often 404; this script uses Wikimedia Commons (+ Simple Icons for Kia).

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/public/logos"
mkdir -p "$DEST"

download() {
  local slug="$1" url="$2"
  curl -sL "$url" -o "$DEST/${slug}.svg"
  echo "Downloaded: ${slug}.svg"
}

# Wikimedia Commons (SVG)
download toyota   "https://upload.wikimedia.org/wikipedia/commons/e/e7/Toyota.svg"
curl -sL "https://cdn.simpleicons.org/kia" -o "$DEST/kia.svg"
echo "Downloaded: kia.svg (Simple Icons — Commons path 404)"
download hyundai  "https://upload.wikimedia.org/wikipedia/commons/9/92/Hyundai_Motor_Company_logo.svg"
download nissan   "https://upload.wikimedia.org/wikipedia/commons/8/8e/Nissan_2020_logo.svg"
download mercedes-benz "https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Logo.svg"
download bmw      "https://upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg"
download honda    "https://upload.wikimedia.org/wikipedia/commons/3/38/Honda.svg"
download chevrolet "https://upload.wikimedia.org/wikipedia/commons/1/1e/Chevrolet_logo.svg"
download ford     "https://upload.wikimedia.org/wikipedia/commons/3/3e/Ford_logo_flat.svg"
download audi     "https://upload.wikimedia.org/wikipedia/commons/9/92/Audi-Logo_2016.svg"
download volkswagen "https://upload.wikimedia.org/wikipedia/commons/6/6d/Volkswagen_logo_2019.svg"
download lexus    "https://upload.wikimedia.org/wikipedia/commons/3/3b/Lexus_-_Logo.svg"
download jeep     "https://upload.wikimedia.org/wikipedia/commons/b/b7/Jeep_logo.svg"
download mitsubishi "https://upload.wikimedia.org/wikipedia/commons/7/7b/Mitsubishi_logo.svg"
download land-rover "https://upload.wikimedia.org/wikipedia/commons/a/a0/Land_Rover_logo.svg"
download porsche  "https://upload.wikimedia.org/wikipedia/commons/a/af/Porsche_logo.svg"
download mazda    "https://upload.wikimedia.org/wikipedia/commons/b/b8/Mazda_logo_with_text.svg"
download volvo    "https://upload.wikimedia.org/wikipedia/commons/3/38/Volvo_logo.svg"
download suzuki   "https://upload.wikimedia.org/wikipedia/commons/1/12/Suzuki_logo_2.svg"
download infiniti "https://upload.wikimedia.org/wikipedia/commons/4/4f/Infiniti_logo.svg"
download cadillac "https://upload.wikimedia.org/wikipedia/commons/3/30/Cadillac_logo.svg"
download dodge    "https://upload.wikimedia.org/wikipedia/commons/e/e8/Dodge_logo.svg"
download peugeot  "https://upload.wikimedia.org/wikipedia/commons/7/73/Peugeot_2021_Logo.svg"
download renault  "https://upload.wikimedia.org/wikipedia/commons/b/b7/Renault_2021_Text.svg"
download tesla    "https://upload.wikimedia.org/wikipedia/commons/b/bb/Tesla_T_symbol.svg"
download mg       "https://upload.wikimedia.org/wikipedia/commons/f/f7/MG_Motor_logo.svg"
download byd      "https://upload.wikimedia.org/wikipedia/commons/b/b5/BYD_Auto_logo.svg"
download haval    "https://upload.wikimedia.org/wikipedia/commons/a/a3/Haval_logo.svg"
download geely    "https://upload.wikimedia.org/wikipedia/commons/b/be/Geely_Auto_logo.svg"
download chery    "https://upload.wikimedia.org/wikipedia/commons/3/3e/Chery_logo.svg"
download mini     "https://upload.wikimedia.org/wikipedia/commons/d/d7/Mini_logo.svg"
download jaguar   "https://upload.wikimedia.org/wikipedia/commons/a/a9/Jaguar_Cars_logo.svg"
download ferrari  "https://upload.wikimedia.org/wikipedia/commons/7/76/Ferrari-Logo.svg"
download lamborghini "https://upload.wikimedia.org/wikipedia/commons/7/7e/Lamborghini-Logo.svg"
download subaru   "https://upload.wikimedia.org/wikipedia/commons/1/1d/Subaru_logo.svg"
download skoda    "https://upload.wikimedia.org/wikipedia/commons/9/9b/%C5%A0koda_Auto_logo.svg"
download opel     "https://upload.wikimedia.org/wikipedia/commons/e/e1/Opel_logo_2017.svg"
download fiat     "https://upload.wikimedia.org/wikipedia/commons/7/71/Fiat_logo.svg"
download buick    "https://upload.wikimedia.org/wikipedia/commons/b/b5/Buick_logo.svg"
download gmc      "https://upload.wikimedia.org/wikipedia/commons/a/a7/GMC_logo.svg"
download lincoln  "https://upload.wikimedia.org/wikipedia/commons/f/f5/Lincoln_Motor_Company_logo.svg"
download acura    "https://upload.wikimedia.org/wikipedia/commons/3/38/Acura_logo.svg"
download genesis  "https://upload.wikimedia.org/wikipedia/commons/8/89/Genesis_Motor_logo.svg"
download alfa-romeo "https://upload.wikimedia.org/wikipedia/commons/a/a8/Alfa_Romeo_logo.svg"
download chrysler "https://upload.wikimedia.org/wikipedia/commons/f/f2/Chrysler_logo.svg"
download rolls-royce "https://upload.wikimedia.org/wikipedia/commons/1/11/Rolls-Royce-Logo.svg"
download bentley  "https://upload.wikimedia.org/wikipedia/commons/b/bf/Bentley_logo.svg"
download ram      "https://upload.wikimedia.org/wikipedia/commons/5/5a/Ram_logo.svg"
download changan  "https://upload.wikimedia.org/wikipedia/commons/1/14/Changan_logo.svg"
download jetour   "https://upload.wikimedia.org/wikipedia/commons/b/b0/Jetour_logo.svg"

echo "Done. Files in $DEST"
