/**
 * Iraq cities and locations for the sell wizard.
 * Sourced from: iqcars_cleaned.csv (location column) + project spec cities.
 * Excludes the CSV header "location". Sorted A–Z for dropdown and search.
 */
export const IRAQ_CITIES: string[] = [
  "Abu Al-Khaseeb",
  "Abu Ghraib",
  "Ad Dayr",
  "Afak",
  "Akre",
  "Al Abassiya",
  "Al Alam",
  "Al Budayr",
  "Al Dawayah",
  "Al Dujayl",
  "Al Duloiya",
  "Al Fajr",
  "Al Hashimiyah",
  "Al Hatamia",
  "Al Hurria",
  "Al Islah",
  "Al Kahla",
  "Al Khas",
  "Al Kuwayr",
  "Al Madina",
  "Al Majer Al Kaber",
  "Al Moshahda",
  "Al Musharrah",
  "Al Mutassim",
  "Al Muwaffaqiyah",
  "Al Nashwa",
  "Al Nasr Wal Salam",
  "Al Neser",
  "Al Obaidy",
  "Al Qasim",
  "Al Qurnah",
  "Al Saniya",
  "Al Seeba",
  "Al Sharish",
  "Al Shirqat",
  "Al shmus",
  "Al Shomali",
  "Al Talieah",
  "Al Uzair",
  "Al Wihda",
  "Al Zab",
  "Al-Abbasi",
  "Albaghdadi",
  "Al-dabuni",
  "Al-Darraji",
  "Al-Diwaniyah",
  "Aldor",
  "Al-Fadliyah",
  "Al-Fallujah",
  "Al-Faw",
  "Al-Fuhud",
  "Al-Hamdaniya",
  "Al-Hamzah",
  "Al-Hartha",
  "Al-Hay",
  "Ali Al-Garbi",
  "Al-jadul gharbi",
  "Al-Khairat",
  "Al-Khidhir",
  "Al-Kifl",
  "Al-Maimouna",
  "Al-majd",
  "Al-Mishikhab",
  "Al-najmi",
  "Al-Qadisiyah",
  "Al-Qadisiyyah",
  "Alqosh",
  "Al-Rumaila",
  "Al-sdair",
  "Al-Shikhan",
  "Al-Slahiya",
  "Al-Suwaira",
  "Altun Kupri",
  "Al-urka",
  "Al-Zubair",
  "Amarah",
  "Amedi",
  "Amerli",
  "Amiriyat Fallujah",
  "Anah",
  "Anbar",
  "Arbat",
  "Ash-Shinafiyah",
  "Ayn al-Tamr",
  "Az Zubaydiyah",
  "Aziziyah",
  "Baashiqah",
  "Babil",
  "Badra",
  "Baghdad",
  "Bahirka",
  "Baiji",
  "Balad",
  "Bardarash",
  "Bartella",
  "Basra",
  "Batha",
  "Bazian",
  "Baqubah",
  "Bub Al-Sham",
  "Chamchamal",
  "Chibayish",
  "Choman",
  "Chwarqurna",
  "Dagharah",
  "Daquq",
  "Darbandikhan",
  "Dhi Qar",
  "Diala",
  "Dibis",
  "Diyala",
  "Dokan",
  "Dohuk",
  "Duhok",
  "Diwaniyah",
  "Erbil",
  "Fahama",
  "Faidah",
  "Fallujah",
  "Gammas",
  "Gassan",
  "Gharraf",
  "Griq",
  "Habbaniyah",
  "Haditha",
  "Hajiawa",
  "Halabja",
  "Harir",
  "Haswa",
  "Hilla",
  "Hillah",
  "Hatra",
  "Hawija",
  "Hayderiyh",
  "Hindiyah",
  "Hit",
  "Hosseinia",
  "Husaybah",
  "Ibrahim Bin Ali",
  "Ishaqi",
  "Kalak",
  "Kalar",
  "Karbala",
  "Karma",
  "Khalidiya",
  "Khalifan",
  "Khor Al Zubair",
  "Khurmal",
  "Kifri",
  "Kirkuk",
  "Koya",
  "Kubaysah",
  "Kufa",
  "Kumayt",
  "Kut",
  "Latifiya",
  "Laylan",
  "Madain",
  "Mahawil",
  "Mahmudiyah",
  "Makhmur",
  "Mangesh",
  "Maysan",
  "Medhatiya",
  "Mosul",
  "Muhanawia",
  "Musayib",
  "Muthanna",
  "Nahrawan",
  "Najaf",
  "Nasiriyah",
  "Nile",
  "Nimrod",
  "Numaniyah",
  "Penjwen",
  "Pirmam",
  "Pshdar",
  "Qa'im",
  "Qala Salih",
  "Qaladiza",
  "Qalat Sukkar",
  "Qara Hanjir",
  "Rabia",
  "Radwaniyah",
  "Ramadi",
  "Ranya",
  "Rasheed",
  "Rawa",
  "Rifai",
  "Riyadh",
  "Rovia",
  "Rumaitha",
  "Rutba",
  "Sabaa Al Bour",
  "Sabiat",
  "Saddat Al-Hindiyah",
  "Safwan",
  "Salahaddin",
  "Samarra",
  "Samawah",
  "Saqlawia",
  "Sayed Taleb",
  "Shafi",
  "Shamia",
  "Shaihemiyh",
  "Shamiyah",
  "Shaqlawa",
  "Shatrah",
  "Shatt al-Arab",
  "Shayk Sa'd",
  "Shwan",
  "Sinjar",
  "Soran",
  "Sulaymaniyah",
  "Sumel",
  "Sumer",
  "Suq Al-Shuyukh",
  "Syed Kheel",
  "Taji",
  "Tajiyat",
  "Tal Abta",
  "Tal Afar",
  "Tall Kayf",
  "Tarmiyah",
  "Taza Khurmatu",
  "Tikrit",
  "Tuz Khurma",
  "Ukaikah",
  "Um Al Shuwayj",
  "Um Qasr",
  "Warte",
  "Wasit",
  "Yathrib",
  "Yusufiya",
  "Zaxo",
  "Zummar",
].filter((c) => c !== "location").sort((a, b) => a.localeCompare(b, "en"))

